server:
  port: 8081
  
spring:
  security:
    user:
      name: demo
      password: "null"
      
  jpa:
#    database: h2
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    #url: "jdbc:postgresql://10.8.1.48:26257/demo?ssl=true&sslmode=require&sslrootcert=/home/hwicaksono/.cockroach-certs/ca.crt&sslkey=/home/hwicaksono/.cockroach-certs/client.demo.key.pk8&sslcert=/home/hwicaksono/.cockroach-certs/client.demo.crt"
    url: "jdbc:postgresql://cockroachdb-public:26257/demo?ssl=true&sslmode=disable"
    username: demo
    password: password
    hikari:
      maximum-pool-size: 5
      connection-test-query: select 1
      