server:
  port: 8081
  
logging:
  level:
    com.jatis.tripatra.demo: debug
    org.springframework.cache: debug
spring:
  security:
    user:
      name: demo
      password: "null"
      
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:~/demo2
    username: demo2
    password: password
    hikari:
      maximum-pool-size: 5
      connection-test-query: select 1
      